### ISSUE TITLE
Can't test a keyboard in jest

### ISSUE THREAD

**Issue by ajeffrey** [hodgef/react-simple-keyboard#140]
**React-simple-keyboard version**
1.25.0

**Describe the bug**
When rendering the keyboard inside enzyme's `mount` function for testing, I get `    ".react-simple-keyboard" was not found in the DOM.` in the console and `KEYBOARD_DOM_ERROR` as an exception.

**Screenshots**
Instead of screenshots, here's a minimal replication case (added to a `create-react-app` project):

`keyboard.spec.tsx`

```typescript
import * as React from 'react';
import { mount } from 'enzyme';
import Keyboard from 'react-simple-keyboard';

describe('Keyboard Component', () => {

  it('should append to the value when a text button is clicked', () => {
    const onChange = jest.fn();

    const target = mount(<Keyboard onKeyPress={onChange} />); // breaks here
    target.find('[data-skbtn=o]').simulate('click');
    expect(onChange).toHaveBeenCalledWith('o');
  });
});
```

**Comment by hodgef** [comment]
Hello @ajeffrey,

You can take a look at the tests here for a working reference:
https://github.com/hodgef/react-simple-keyboard/blob/master/src/lib/components/tests/Keyboard.test.js

Hope that helps.

Regards,
Francisco Hodge

**Comment by ajeffrey** [comment]
I'll give that a try, thanks!

**Comment by ajeffrey** [comment]
it looks as though the `setDOM` utility isn't available in the npm package? Without it I managed to get my first test working, but the second failed. It currently looks like this:

```typescript
import * as React from 'react';
import { mount } from 'enzyme';
import SimpleKeyboard from 'react-simple-keyboard';
import Keyboard from '.';

const root = document.createElement('div');
root.id = 'root';
document.body.appendChild(root);

const getTarget = props => mount(<Keyboard {...props} />, { attachTo: root });

describe('Keyboard Component', () => {
  it('should append to the value when a text button is clicked', (done) => {
    const onChange = jest.fn();
    const value = 'hell';

    const target = getTarget({ onChange, value });
    process.nextTick(() => {
      (target.find(SimpleKeyboard).find('[baseClass="alpha"]').instance() as SimpleKeyboard).keyboard.getButtonElement('o').onclick();
      expect(onChange).toHaveBeenCalledWith('hello');
      done();
    });
  });

  it('should remove a character when the backspace is pressed', (done) => {
    const onChange = jest.fn();
    const value = 'hello';

    const target = getTarget({ onChange, value });
    process.nextTick(() => {
      (target.find(SimpleKeyboard).find('[baseClass="alpha"]').instance() as SimpleKeyboard).keyboard.getButtonElement('{bksp}').onclick()
// fails on the line above: "    Method “instance” is meant to be run on 1 node. 0 found instead."
      expect(onChange).toHaveBeenCalledWith('hell');
      done();
    });
  });
});

```

if I comment out the first test or the second, it works, so it appears to be a shared resource problem. Presumably setDOM helps with this?

**Comment by hodgef** [comment]
Hello @ajeffrey,

You can find `setDom` here:
https://github.com/hodgef/react-simple-keyboard/blob/master/src/utils/TestUtility.js#L3

All that it does is to create a container div and append it to `document.body`. Similarly to what you've done.

Then, in Jest we mount the keyboard to this container (the firstChild of body):
`mount(<Keyboard />, { attachTo: document.body.firstChild });`

The `Keyboard` declaration is as follows:
```
import Keyboard from 'react-simple-keyboard';
```

I recommend closely following [this test](https://github.com/hodgef/react-simple-keyboard/blob/master/src/lib/components/tests/Keyboard.test.js) as a reference. Doing so would help you mitigate any errors.

For instance, instead of this:
```
(target.find(SimpleKeyboard).find('[baseClass="alpha"]').instance() as SimpleKeyboard).keyboard.getButtonElement('o').onclick();

```

I would write this:
```
wrapper.instance().keyboard.getButtonElement("o").onclick();
```
https://github.com/hodgef/react-simple-keyboard/blob/master/src/lib/components/tests/Keyboard.test.js#L60

I'm not sure if adding the enzyme adapter would help also, but it'd be worth giving it a try. My take is that if your tests differs from the [working tests](https://github.com/hodgef/react-simple-keyboard/blob/master/src/lib/components/tests/Keyboard.test.js), then to debug you should start from the working tests then go from there.

Regards,
Francisco Hodge

**Comment by ajeffrey** [comment]
Hi Francisco, I amended my tests by creating a new root element per test (similar to your setDOM utility) and it all works now. Thanks for your help!

**Comment by hodgef** [comment]
Glad to hear :smiley:  Let me know if you run into any other issues!
