### ISSUE TITLE
Is it possible to use an input ref for to hold keyboard values?

### ISSUE THREAD

**Issue by seloner** [hodgef/react-simple-keyboard#1408]
I am using the latest version .
My issue is that I want to use the virtual keyboard and the device keyboard at the same time.
In the examples to do that you need to update the keyboard value when the value of the input changes so virtual keyboard and HTML input are synced.
Is there any way to have one place of truth to hold the value?
For example to pass the input ref into the virtual keyboard.

**Comment by hodgef** [comment]
Hello @seloner,

Long story short, this is not possible.

The logic of simple-keyboard (the vanilla JS library) is based around handling the input within the library ([`keyboard.input` object](https://github.com/hodgef/simple-keyboard/blob/1b5a0f711388837ba232420d8f05ba2ea6bb4023/src/lib/components/Keyboard.ts#L167)) and giving options to the user to get/set this value through simple-keyboard's callbacks or methods.

The main reason is that in simple-keyboard/vanilla JS there's no two way binding. So if you're typing on an input element directly it's already expected to use the `change` event in order to update any places that depend on that value.

react-simple-keyboard is just a wrapper for the vanilla JS library, so it follows the same pattern.

Hope that makes it a bit clearer.
Francisco Hodge
