### ISSUE TITLE
How do i get capital letters in the onKeyPress event handler ? (As of now we get only the small letters)

### ISSUE THREAD

**Issue by PRAVEENRP1047** [hodgef/react-simple-keyboard#1712]
import React, { Component } from "react";
import { render } from "react-dom";
import Keyboard from "react-simple-keyboard";
import "react-simple-keyboard/build/css/index.css";
import "./index.css";

class App extends Component {
  state = {
    layoutName: "default",
    input: ""
  };

  onKeyPress = (button) => {
    console.log(button, "button pressed");
  };

  render() {
    return (
      <div>
        <Keyboard
          onKeyPress={this.onKeyPress}
          physicalKeyboardHighlight={true}
          physicalKeyboardHighlightPress={true}
          physicalKeyboardHighlightTextColor="#fff"
          physicalKeyboardHighlightBgColor={"#3295db"}
        />
      </div>
    );
  }
}

render(<App />, document.getElementById("root"));

**Comment by hodgef** [comment]
Hello @PRAVEENRP1047,

Set the `layoutName` to "shift" in order to get the shift layout. Check out the following demo to understand the various options and customization possibilities:

https://hodgef.com/simple-keyboard/editor/?d=hodgef/react-simple-keyboard-demos/tree/uc-customization

Regards,
Francisco Hodge

**Comment by PRAVEENRP1047** [comment]
Thank you very much @hodgef .
