### ISSUE TITLE
How to get this keyboard to work with shadow-dom?

### ISSUE THREAD

**Issue by robergwillian** [hodgef/react-simple-keyboard#1716]
Hello!

First of all, great work on this keyboard, I have it fully functional on my application with react and it works great.

My question is, I have another project that uses shadow-dom, and when I implement it the same way I did on the other project I get a Keyboard_dom_error.

I've tryed to add the simple-keyboard div inside the shadow-root-document but that didn't work, could you shed some light as to how to get this to work? This app is also build in react with shadow-dom

Thanks

**Comment by hodgef** [comment]
Hey @robergwillian,

You normally get [KEYBOARD_DOM_ERROR](https://hodgef.com/simple-keyboard/questions-answers/fix-keyboard-dom-error/) when the container div is not found when the constructor is fired. This is not likely to happen in React (where `react-simple-keyboard` is likely to be used) since the [div is added in the renderer](https://github.com/hodgef/react-simple-keyboard/blob/d156d7bbedf8e17cd1294586d728d42260427a1e/src/lib/components/Keyboard.tsx#L45) and [the constructor is called in the `useEffect`](https://github.com/hodgef/react-simple-keyboard/blob/d156d7bbedf8e17cd1294586d728d42260427a1e/src/lib/components/Keyboard.tsx#L24).

So my questions are:

- Are you using `react-simple-keyboard`?
- If not, is there a reason why you chose this approach? (Generally React users opt for `react-simple-keyboard`).
- Could you provide a repro that I could look into (e.g.: a test git repo or fork of one of the demo sandboxes?)

There's many things that could cause an issue, but they're most likely related to setup so a repro will definitely help.

I will reopen once I get the repro, thanks!

**Comment by robergwillian** [comment]
Hey, thanks for you quick reply.

I'm using the react-simple-keyboard. I created a copy of the repo I'm using, its a private, but I've added you to have access to it.

branch: ew-249-custom-keyboard

my keyboard component is at components/common/keyboard

and the keyboard is used at components/signup/primaryinfo/index

on the app main index you will see some commented lines, those lines switch between using the regular dom or the shadow-dom, if you uncomment those lines and comment the shadow-dom, the keyboard works fine, but when using the shadow-dom we get the error and the keyboard will not show up. 

let me know if I can clarify anything else

**Comment by hodgef** [comment]
Hi @robergwillian,

I have pushed an update to react-simple-keyboard@3.4.31 which should _partially_ address this use-case.

The keyboard should now render normally (no more `KEYBOARD_DOM_ERROR`). However, imported styles are not being added at the ShadowRoot level. I'm not sure if this is due to missing Webpack configuration or otherwise, but I think diving into potential Webpack tweaking goes beyond my scope.

If you do find a solution for this please let me know. I will make sure to update this thread if I come across any new info.

Regards,
Francisco Hodge
