### ISSUE TITLE
Useless updates being released almost every day

### ISSUE THREAD

**Issue by korbav** [hodgef/react-simple-keyboard#1718]
Hi, correct me if I am wrong but it seems that almost daily updates are being released, without any content except an increased version number.

This is definitely not a big issue but there must be some unexpected setup in Github actions.

**Comment by hodgef** [comment]
Hello @korbav,

This is due to Dependabot updates. The goal is to reduce manual work, to make sure that the release was built with the latest tooling (which could bring along optimizations or patches) and to be aware of any breaking changes as they come (through failing tests).

**Here's an example of Dependabot PRs:**
https://github.com/hodgef/react-simple-keyboard/pull/1717 (passed, triggered release)
https://github.com/hodgef/react-simple-keyboard/pull/1715 (did not pass, no release)

**Here's the Dependabot settings:**
https://github.com/hodgef/react-simple-keyboard/blob/master/.github/dependabot.yml

**And the GH actions:**
https://github.com/hodgef/react-simple-keyboard/blob/master/.github/workflows/pull_request_dependabot.yml
https://github.com/hodgef/react-simple-keyboard/blob/master/.github/workflows/publish.yml

I used to have these updates weekly, but then I had a huge backlog that flooded the Discord channel. This is why the updates have been nightly for the past year or so.

If you'd rather not have simple-keyboard updates so often you can tweak your updater/GH actions setup accordingly. Let me know if you have any questions or concerns.

Thanks,
Francisco Hodge
