### ISSUE TITLE
Physical keyboard backspace is not detected

### ISSUE THREAD

**Issue by LibreTechie** [hodgef/react-simple-keyboard#1753]
***react-simple-keyboard version: 3.4.45***

I'm include a keyboard in my project with the below code snippet.
```
          <Keyboard
            keyboardRef={r => this.keyboard = r}
            onKeyPress={this.onKeyPress.bind(this)}
            layoutName='default'
            layout={{
              'default': [
                'Q W E R T Y U I O P',
                'A S D F G H J K L',
                '{enter} Z X C V B N M {bksp}',
              ]
            }}
            display={{
              '{enter}': 'ENTER',
              '{bksp}': '&lArr;'
            }}
            physicalKeyboardHighlight={true}
            physicalKeyboardHighlightPress={true}
          />
```

In my application - I want to allow users to use both on screen board and physical keyboard for input. With the above code snippet, all capital letters and enter key on physical keyboard are detected. But the backspace press is not detected.

How can I handle this issue?

**Comment by hodgef** [comment]
Hello @LibreTechie,

In the docs for `physicalKeyboardHighlight` there's some details:

> For functional keys such as shift, note that the key’s event.code is used. In that instance, pressing the left key will result in the code ShiftLeft. Therefore, the key must be named {shiftleft}.

https://hodgef.com/simple-keyboard/documentation/options/physicalkeyboardhighlight/

This is why in the demo linked in that page we see `{backspace}` instead of `{bksp}`.

![image](https://user-images.githubusercontent.com/25509135/151714267-64fb9c84-3f27-46a8-8d0c-148afe580ed6.png)

Regards,
Francisco Hodge

**Comment by LibreTechie** [comment]
@hodgef It is working now with this handling. Thanks.
