### ISSUE TITLE
Problem building app with Next.js

### ISSUE THREAD

**Issue by joselegitan** [hodgef/react-simple-keyboard#197]
Hello,

I have integrated react-simple-keyboard@2.0.3 in my app using the Next.js framework (next@9.0.5). when I try to build the app i've got : 
../node_modules/react-simple-keyboard/build/css/index.css
BrowserslistError: Unknown browser query `dead`

is there a way to correct it ? specific webpack version or other ?

Thank you in advance.
Regards,

**Comment by hodgef** [comment]
Hello @joselegitan,

This is a specific issue with loading css files with Next.js, not really a simple-keyboard issue. For these kind of issues StackOverflow would be more helpful:

https://stackoverflow.com/a/50169230/1467941

Now, after fixing that you may notice build will throw another error:

![image](https://user-images.githubusercontent.com/25509135/64626831-82021e00-d3bc-11e9-8484-51e59bf32912.png)

This is since simple-keyboard requires `window` to exist, which causes issues with SSRs on build.

To fix this, please follow the instructions in the Getting Started docs, under "Usage with Gatsby and similar static site generators".

https://simple-keyboard.com/react/getting-started/

Regards,
Francisco Hodge
