### ISSUE TITLE
Cannot read properties of undefined (reading 'length') when clearing input 

### ISSUE THREAD

**Issue by sophielevens** [hodgef/react-simple-keyboard#2032]
**React-simple-keyboard version**
Version `3.4.191`

**Describe the bug**
When backspace is pressed I get an error that says `Cannot read properties of undefined (reading 'length')`. I can see that the error comes from `react-simple-keyboard`'s node modules so wanted to ask if you know what's causing it?

It might be that i am setting the inputs incorrectly when backspace is pressed, but I'd really appreciate if you could take a look 👀 

[Code sandbox here](https://codesandbox.io/s/solitary-forest-722dhe?file=/src/keyboard.tsx) - please note that the styles aren't working on the sandbox (not sure why).

Many thanks for the upkeep of this repo 💪  
**Screenshots**
![image](https://user-images.githubusercontent.com/25961258/186696300-28601235-6a8b-40fd-bf9e-c49a29425469.png)

https://user-images.githubusercontent.com/25961258/186696679-9272fa8f-009f-41fb-be84-3e48974a0a5d.mov

**Comment by hodgef** [comment]
Hey @sophielevens, yes this is definitely caused by the logic in the `onKeyPress`, because if you comment that out the issue is gone.

This is the best I could do to fix it with the time I had:
https://codesandbox.io/s/busy-keller-3lymw6?file=/src/keyboard.tsx

It's still not the best but I'm sure you can take it from there.

Some tips:
- use `debug={true}` & `console.log` the keyboard properties such as `keyboard.current.input`.
- simple-keyboard keeps it's own internal state, so make sure to compare it with your local state (this goes with the previous comment).

Cheers,
Francisco Hodge

**Comment by sophielevens** [comment]
@hodgef thanks so much for your speedy reply and taking a look 🙏
