### ISSUE TITLE
physicalKeyboardHighlight doesn't consistently pass events to onKeyPress and onKeyReleased callbacks

### ISSUE THREAD

**Issue by Patchnote-v2** [hodgef/react-simple-keyboard#2565]
**react-simple-keyboard:  3.7.31**

**Describe the bug**
Events are almost never passed to the `onKeyPress` and `onKeyReleased` callbacks when using the `physicalKeyboardHighlight[...]` options.  It's impossible to have both `onKeyPress` and `onKeyReleased` called _and_ have the event passed to both of them, as well as no way to have `onKeyReleased` fire and have the event properly passed to it.  It's important to note that any combination of `physicalKeyboardHighlight[...]` options will not be able to have an event properly passedto `onKeyReleased`, but you _can_ have an event properly passed to _only_ `onKeyReleased`.  See fig. 1 in screenshots for an example of what I mean.

I did find #2231 which implies that onKeyReleased should be receiving the event, but I cannot get it to do so.

**Provide a repro**
[Here is just the basic React demo](https://codesandbox.io/embed/unruffled-panka-n72mrc) with some debug console.logs thrown in.  As you can see, clicking on a key sends the event to a both `onKeyPress` and `onKeyReleased`, but typing on your keyboard does not.  I can't have every variation of options as in the chart below in a single sandbox but I tested some of them to ensure that they were consistent with my local testing.

**Screenshots**
Assuming that `physicalKeyboardHighlight` was _always_ `true` for the tests I did, the chart below shows the behavior of every permutation of every relevant `physicalKeyboardHighlight[...]` option (i.e. excluding TestColor and BgColor options).  As you can see there's no way to have `onKeyReleased` fire and have the event passed to it, as well as also no way to have both callbacks called and have the event passed to both of them.

![image](https://github.com/hodgef/react-simple-keyboard/assets/11915225/6318bee2-c348-4498-85e5-df8d95c29bae)

Perhaps I am misunderstanding something fundamental about the options in question.  I've looked at both Keyboard.ts and PhysicalKeyboard.ts but I don't understand it the design enough to know why it is functioning this way.

As a side, it seems that [the docs](https://hodgef.com/simple-keyboard/documentation/options/) are missing some valid options.  Namely, the three relevant to my issue are `physicalKeyboardHighlightPressUsePointerEvents`, `physicalKeyboardHighlightPressUseClick`, and `physicalKeyboardHighlightPreventDefault`.

**Comment by hodgef** [comment]
Hello @Patchnote-v2,

I have added a change to pass the event in the pointer events scenario:
https://github.com/hodgef/simple-keyboard/commit/320878f93cb6cdf38b8740dad5f0c5675015b95b

You can use the following options:
```js
physicalKeyboardHighlight: true,
physicalKeyboardHighlightPress: true,
physicalKeyboardHighlightPressUsePointerEvents: true
```
_______________
I hear the concerns raised in your ticket. Here's some context from my side:

### Undocumented functions
> As a side, it seems that [the docs](https://hodgef.com/simple-keyboard/documentation/options/) are missing some valid options

The issue about undocumented options is as follows: people ask for fixes and sometimes I can deliver fast by doing a quick code change. However, since my time is limited, the docs website can fall behind. I believe this is less of an issue though because these functions are not advertised anyway beyond InteliSense.

As a note for searchers: any undocumented function originates from a Github issue, so people can find context by using Git blame. I normally link the responsible issue in the commit message:

For example: https://github.com/hodgef/simple-keyboard/blame/2db277f3eb0742dfa9bc64c88f0b6f65d2642de6/src/lib/components/Keyboard.ts#L111

![image](https://github.com/hodgef/react-simple-keyboard/assets/25509135/3f7a5349-28ea-4e11-a778-0ab3517e52fb)
![image](https://github.com/hodgef/react-simple-keyboard/assets/25509135/55c367ec-736c-4261-b051-037540a7fdc3)

### Debugging simple-keyboard
> I don't understand it the design enough to know why it is functioning this way

Here's how you can debug simple-keyboard locally:
https://github.com/hodgef/simple-keyboard#to-run-demo-on-your-own-computer

In there you can add breakpoints and check out the Call Stack (to see what called what).
![image](https://github.com/hodgef/react-simple-keyboard/assets/25509135/f75c92db-fa64-466f-b1cb-b2178cc0ec53)

**Optional:** If you want to fix a React-only issue you can do this in your local react-simple-keyboard: `npm install C:\path-to-simple-keyboard`

Hopefully this helps people get unblocked and feel more comfortable raising PRs. I still have visibility and can jump in to help in my spare time, but unfortunately not as fast as in 2018 (especially for those issues that are niche and not being reported by many people).
