### ISSUE TITLE
Caret function

### ISSUE THREAD

**Issue by datnordstrom** [hodgef/react-simple-keyboard#32]
I use react-autocomplete and selecting an item doesn't set the caret to the end of the string unless a user selects the input again.

If there is a way to manually set this, to easily control the caret this would solve this issue and others..

**Comment by hodgef** [comment]
Hello @datnordstrom,

`The caret position is at this.keyboardRef.keyboard.caretPosition`. You can change it directly as needed. If you set it to null, it will default to the end of the input.

Here's an example (will delete after issue closing due to codesandox limits):
https://codesandbox.io/s/qk3ww892yq (line ~23)

If you would like to disable caret positioning, you can set the prop `disableCaretPositioning={false}`.
This will result in characters being always added/removed at the end of the input string.

If you still have issues or questions, let me know and I'll reopen the ticket.

____
**More info regarding caret behavior**
The caret is set when you click or type (with the physical keyboard) inside an input or textarea. It also moves when you type with simple-keyboard. If the caret position is null, simple-keyboard will default to adding/removing characters at the end of the string.

Regards,
Francisco Hodge

**Comment by chapster11** [comment]
Hi I'm using useRef() and when I do the following its not updating the caretPosition of the keyboard as suggested above. 
```
const keyboard = useRef();
// in a blur event from an input field I'm trying to set the keyboard.caretPosition. 
keyboard.caretPosition = 1
```

The above does not update the keyboard caretPosition as its a read only property.
There is a getCaretPosition() 
would it be possible to expose a setCaratPosition().
