### ISSUE TITLE
disableCaretPositioning is not working based on condition by setting true and false.

### ISSUE THREAD

**Issue by rajdoshi9089** [hodgef/react-simple-keyboard#37]
**React-simple-keyboard version**
As some bugs have been addressed in later versions, please ensure you are running the latest.

**Describe the bug**

**Screenshots**

**Comment by hodgef** [comment]
Hello @rajdoshi9089,

As I said on ticket #36, I will need a [sandbox example](https://codesandbox.io/s/new) to see the problem. Otherwise I really have no context about what's going on.

I'm closing this one out until you provide a sandbox example, or code which will help me understand your implementation issues.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Hello @rajdoshi9089,

I was able to identify the issue in another ticket. This should now be fixed as of the latest version.
Details here: https://github.com/hodgef/react-simple-keyboard/issues/38#issuecomment-455376966

Regards,
Francisco Hodge
