### ISSUE TITLE
Need a support Type script

### ISSUE THREAD

**Issue by CrazyAdmin** [hodgef/react-simple-keyboard#39]
Add the index.d.ts file

**Comment by hodgef** [comment]
Hey @CrazyAdmin ,

Very valid request. I'll be shipping this sometime this week.

If you'd like to use the feature right now, you can use simple-keyboard directly (instead of the react port).

https://github.com/hodgef/simple-keyboard
https://github.com/hodgef/simple-keyboard/blob/master/src/lib/%40types/index.d.ts

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Hey @CrazyAdmin,

react-simple-keyboard now supports Typescript (as of `1.16.0`) !
This should address this issue. If you see any issues pop up feel free to let me know.

Here's an example:
https://github.com/hodgef/react-simple-keyboard-typescript-demos/blob/master/src/App.tsx

I will set up a codesandbox demo and update the docs shortly.

Regards,
Francisco Hodge

**Comment by CrazyAdmin** [comment]
Thank you so much !!!!
