### ISSUE TITLE
propsChanged check doesn't detect function prop changes

### ISSUE THREAD

**Issue by GlynL** [hodgef/react-simple-keyboard#423]
**React-simple-keyboard version**
^2.1.114

**Describe the bug**
The propsChanged helper doesn't detect if the prop that changed is a function. 
JSON.stringify strips out methods from objects.
```
JSON.stringify({a: () => console.log('hey')})
"{}"
```

**Comment by hodgef** [comment]
Hey @GlynL,

The intent of that check is to know when an option (generally booleans, objects or strings) has changed in order to call [`setOptions`](https://github.com/hodgef/react-simple-keyboard/blob/afb854aa3acea410d21e264bc8fff57474d3a060/src/lib/components/Keyboard.js#L29).

Here's the doc entry for `setOptions`: https://simple-keyboard.com/documentation/#setOptions

I understand `onKeyPress` and such are filed under "options", but they are more like callbacks. For example, I wouldn't use `setOptions` to set my `onKeyPress` callback. I generally would add that callback at init. (In React terms: I normally wouldn't change a callback prop for another).

That being said, I explored other deep equal functions but they are either more verbose or require dependencies. Please feel free to propose a PR and I'll take a look.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Hello @GlynL,

Looking back at this bug, it seems to be valid and worth fixing ASAP. Sorry for closing it incorrectly earlier this year.

I'll provide a fix ASAP.

**Comment by jmadelaine** [comment]
I've just opened #545 but this is the same issue.

> The intent of that check is to know when an option (generally booleans, objects or strings) has changed in order to call setOptions

If options are considered separate to callbacks, then there should probably be a check on the options passed rather than a check on all props. React also has `memo` which can be used if you want to compare props with previous values before re-rendering.

**Comment by hodgef** [comment]
Thanks @jmadelaine. I'll close this in favor of #545. I'll track progression there.

Regards,
Francisco Hodge
