### ISSUE TITLE
The bug of preventMouseDownDefault

### ISSUE THREAD

**Issue by gd-ldj** [hodgef/react-simple-keyboard#44]
**Describe the bug**

After using this preventMouseDownDefault, when you insert the cursor in the middle of the input word, the cursor changes to the end.

**Screenshots**
![image](https://user-images.githubusercontent.com/34954129/54992096-64e9b680-4ff9-11e9-85d3-efa515b0d7f9.png)

**Comment by hodgef** [comment]
Hello @gd-ldj,

This is a [known issue](https://github.com/hodgef/simple-keyboard/pull/39#issuecomment-441455375), but somewhat outside of the scope of simple-keyboard.

Basically, all the `preventMouseDefault` option does it's to add `event.preventDefault()` on button click. The issue lays with the input element (which the library does not manage). When you press a simple-keyboard button, simple-keyboard updates its internal caret value, but the input's `selectionStart` value is not updated (as simple-keyboard doesn't manage input elements).

This issue can be fixed by setting the input's caret position in the onChange callback, like so:
https://codesandbox.io/s/github/simple-keyboard/react-simple-keyboard-preventmodefault-caret-pos/tree/master/

I will add this information to the docs shortly.

Thanks!
Francisco Hodge

**Comment by gd-ldj** [comment]
I get. Thanks!

**Comment by gd-ldj** [comment]
Hello @hodgef ,
I found a new problem with this preventMouseDefault. When I set preventMouseDefault=true, press a key on the keyboard for a while, move it out of the keyboard area, then release it, it will appear all the time.
![image](https://user-images.githubusercontent.com/34954129/56275631-ac182280-6133-11e9-9e20-e028a224ba79.png)

**Comment by hodgef** [comment]
Hello @gd-ldj,

Thanks for reporting this issue. Could you please create a new ticket for it?

Regards,
Francisco Hodge

**Comment by gd-ldj** [comment]
ok
