### ISSUE TITLE
Allow for setCaratPosition on keyboard

### ISSUE THREAD

**Issue by chapster11** [hodgef/react-simple-keyboard#616]
**Is your feature request related to a problem? Please describe.**
Based on this ticket https://github.com/hodgef/react-simple-keyboard/issues/32 it says you can updated the keyboards caretPosition. From wt i'm seeing this is a read only property. 

**Describe the solution you'd like**
Allow a setCaratPosition() method so we can update the keyboards caret position.

I'm using React.useRef() and when I try to access the keyboards caretPosition to update its value based on the following ticket's information https://github.com/hodgef/react-simple-keyboard/issues/32

```
const keyboard = useRef();
// in a blur event from an input field I'm trying to set the keyboard.caretPosition. 
  const onBlur = (event) => {
    keyboard.current.caretPosition = event.target.selectionStart;
  };
```
The above does not update the keyboard caretPosition. Or the key vents on the keyboard is getting to first. Not sure which is the case ?  The keyboard is taking the previous position and not they set one through  keyboard.current.caretPosition

would it be possible to expose a setCaratPosition().

**Comment by hodgef** [comment]
Hello @chapster11,

Are you using the option [`preventMouseDownDefault`](https://hodgef.com/simple-keyboard/documentation/options/preventmousedowndefault/)? I think you would need that to keep the focus on the input while you use simple-keyboard.

The caret position seems to be changed just fine in this example:
https://codesandbox.io/s/objective-frog-wm2xb?file=/src/index.js

Feel free to check it out and let me know if it still doesn't work for you.

Thanks,
Francisco Hodge

**Comment by chapster11** [comment]
Thanks Francisco, I tried your codesandbox on a surface pro and using the touch keyboard. You will see it shows a blue bubble that you can drag to set the new caret position. When you reposition this indicator and then click a key on the keyboard the keyboard does not update the new character in the right place. What its doing is adding the character to the last touched position. 

![IMG_3877](https://user-images.githubusercontent.com/1189450/83480093-54c83500-a44f-11ea-8d86-326b94f9b5d1.jpg)

**Comment by hodgef** [comment]
Hey @chapster11,

Are you using Edge? There was an issue with the browser not updating the caret position when the input bubble was moved.

https://github.com/hodgef/simple-keyboard/issues/54

simple-keyboard relies on [`element.selectionStart`](https://webplatform.github.io/docs/dom/HTMLInputElement/selectionStart/) to update the caret position. Unfortunately, if the browser doesn't update this value when you drag the blue bubble, it's a browser bug and there's not much I can do about it.
 

As a test, you can try this sandbox:
https://jsfiddle.net/zwj82ogb/

If you see the "selectionStart" update as you drag the blue bubble, then it works. Otherwise, there's a browser issue to be reported.

Here's a similar issue filed by one of our users recently regarding caretPosition, this time for Chrome:
https://bugs.chromium.org/p/chromium/issues/detail?id=1073750

Regards,
Francisco Hodge

**Comment by chapster11** [comment]
Thanks @hodgef for looking into this issue and positing another link. 
I'm using chromium on electron.  

Yea I spent all day yesterday trying to get an event to fire for this input indicator with no luck. My last ditched attempt was trying to get the blur from the input to fire before the key event on the keyboard in hopes that I might be able to  update the keyboard caret position before the key got pressed. 

But yes you are right your sandbox does not fire either.
Going to report a bug for this in Chromium.
