### ISSUE TITLE
Issues with backspace when using form masks

### ISSUE THREAD

**Issue by ShadTK** [hodgef/react-simple-keyboard#7]
Hello!

I've been using your plugin for a feature in my app, and so far it's pretty good!

But I'm having a bit of an issue with the backspace. If the target field has some sort of mask (such as react-input-mask), the backspace doesn't work properly.

As far as I could track, this is caused because the input field value and the inner keyboard value are "different" when a mask is applied. I.E: If I have a phone mask, the input field value turns into (30)1234-5678, while the keyboard value is 3012345678

If I touch outside of the input and then inside again, on the last digit, the debug will show me that I clicked on position "12" due to the extra characters, even though the inner keyboard input value only has 9 positions. 

And so, if I try to delete the information from the input field, I have to press the backspace button 3 times until the field starts to be deleted.

Is there any way, currently, to circumvent this issue so that the keyboard input value "adjusts" to the actual input value!

Thanks in advance!

Marcos Rodrigues

**Comment by hodgef** [comment]
Hello Marcos @ShadTK ,

Thanks a lot for reporting this, your debug info has been really useful.

Since simple-keyboard uses an internal input, it doesn't really know the stuff react-input-mask is doing to the input element afterward. You'd have to update simple-keyboard's input, but there are other hurdles:

I noticed that whenever I'm deleting characters using simple-keyboard's `{bksp}`, it stays stuck at `(55)` since `react-input-mask` keeps adding that last `)`.

So I ended up doing this as a workaround:

1. On simple-keyboard's onChange, I update simple-keyboard's internal input (using `keyboard.setInput`).
2. I disable caretPositioning (input is appended/removed at the end of the string only), since every time I add a letter not allowed by `react-input-mask`, simple-keyboard doesn't know that `react-input-mask` will not allow it, so it will still move the caret forwards. You can re-enable caret positioning (line 60 of the following demo) if you have a layout only comprised of characters allowed by your input mask.
3. When deleting, I detect if the character to be deleted is a ")", in which case I trim two characters instead of one... This is to counter `react-input-mask`'s behavior of re-adding the parentheses whenever it's removed.
4. Since `react-input-mask` is limiting character length, I add the `maxLength` option to simple-keyboard as well.

**Demo:** https://codesandbox.io/s/23vy26qq2r

Please let me know if this addresses the problem. If not I'll reopen the ticket :) I'll be definitely be adding this to the [use-cases docs](https://franciscohodge.com/projects/react-simple-keyboard/qa-use-cases/) for future reference.

PS: If you see "Caret position" logs even with debug={false}, it's a codesandbox bug ;)

Regards,
Francisco Hodge
